'use client';

import { useState, useEffect } from 'react';

export type Language = 'en' | 'fa' | 'ar';

const translations = {
  en: {
    selectRole: 'Select Your Role',
    selectRoleDescription: 'Choose the option that best describes you',
    student: 'Student',
    studentDescription: 'Currently enrolled in medical education',
    graduate: 'Graduate',
    graduateDescription: 'Completed medical degree',
    company: 'Company',
    companyDescription: 'Healthcare or pharmaceutical company',
    continue: 'Continue',
    back: 'Back',
    profileInformation: 'Profile Information',
    profileDescription: 'Tell us about yourself',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    phone: 'Phone Number',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    nationality: 'Nationality',
    city: 'City',
    selectCity: 'Select city',
    selectGender: 'Select gender',
    required: 'Required',
    province: 'Province',
    selectProvince: 'Select province',
    searchProvince: 'Search province...',
    noProvinceFound: 'No province found',
    searchCity: 'Search city...',
    noCityFound: 'No city found',
    selectProvinceFirst: 'Please select a province first',
    educationInformation: 'Education Information',
    addCurrentEducation: 'Add your current and completed education',
    educationHistory: 'Education History',
    addCompletedEducation: 'Add your completed education degrees',
    education: 'Education',
    university: 'University',
    enterUniversity: 'Enter university',
    degree: 'Degree',
    enterDegree: 'Enter degree',
    specialty: 'Specialty',
    enterSpecialty: 'Enter specialty',
    startYear: 'Start Year',
    endYear: 'End Year',
    selectYear: 'Select year',
    status: 'Status',
    inProgress: 'In Progress',
    completed: 'Completed',
    addEducation: 'Add Education',
    companyInformation: 'Company Information',
    enterCompanyDetails: 'Enter your company details',
    companyName: 'Company Name',
    enterCompanyName: 'Enter company name',
    companyType: 'Company Type',
    selectType: 'Select type',
    pharmaceutical: 'Pharmaceutical',
    medicalEquipment: 'Medical Equipment',
    insurance: 'Insurance',
    address: 'Address',
    enterCompanyAddress: 'Enter company address',
    website: 'Website',
    establishedYear: 'Established Year',
    employeeCount: 'Employee Count',
    enterEmployeeCount: 'Enter employee count',
    enterPhoneNumber: 'Enter phone number',
    description: 'Description',
    tellAboutCompany: 'Tell us about your company',
    reviewInformation: 'Review Your Information',
    verifyBeforeSubmit: 'Please verify all information before submitting',
    profileDetails: 'Profile Details',
    educationDetails: 'Education Details',
    companyDetails: 'Company Details',
    name: 'Name',
    contactInfo: 'Contact Info',
    edit: 'Edit',
    submit: 'Submit Registration',
    submitting: 'Submitting...',
    role: 'Role',
    profile: 'Profile',
    details: 'Details',
    review: 'Review',
    selectUniversity: 'Select university',
    searchUniversity: 'Search university...',
    noUniversityFound: 'No university found',
    selectDegree: 'Select degree',
    searchDegree: 'Search degree...',
    noDegreeFound: 'No degree found',
    selectSpecialty: 'Select specialty',
    searchSpecialty: 'Search specialty...',
    noSpecialtyFound: 'No specialty found',
  },
  fa: {
    selectRole: 'نقش خود را انتخاب کنید',
    selectRoleDescription: 'گزینه‌ای که شما را بهتر توصیف می‌کند انتخاب کنید',
    student: 'دانشجو',
    studentDescription: 'در حال تحصیل در رشته پزشکی',
    graduate: 'فارغ‌التحصیل',
    graduateDescription: 'دارای مدرک پزشکی',
    company: 'شرکت',
    companyDescription: 'شرکت بهداشتی یا داروسازی',
    continue: 'ادامه',
    back: 'بازگشت',
    profileInformation: 'اطلاعات پروفایل',
    profileDescription: 'درباره خود بگویید',
    firstName: 'نام',
    lastName: 'نام خانوادگی',
    email: 'ایمیل',
    phone: 'شماره تلفن',
    dateOfBirth: 'تاریخ تولد',
    gender: 'جنسیت',
    male: 'مرد',
    female: 'زن',
    other: 'سایر',
    nationality: 'ملیت',
    city: 'شهر',
    selectCity: 'انتخاب شهر',
    selectGender: 'انتخاب جنسیت',
    required: 'الزامی',
    province: 'استان',
    selectProvince: 'انتخاب استان',
    searchProvince: 'جستجوی استان...',
    noProvinceFound: 'استانی یافت نشد',
    searchCity: 'جستجوی شهر...',
    noCityFound: 'شهری یافت نشد',
    selectProvinceFirst: 'لطفاً ابتدا استان را انتخاب کنید',
    educationInformation: 'اطلاعات تحصیلی',
    addCurrentEducation: 'تحصیلات فعلی و گذشته خود را اضافه کنید',
    educationHistory: 'سوابق تحصیلی',
    addCompletedEducation: 'مدارک تحصیلی تکمیل شده خود را اضافه کنید',
    education: 'تحصیلات',
    university: 'دانشگاه',
    enterUniversity: 'نام دانشگاه را وارد کنید',
    degree: 'مقطع',
    enterDegree: 'مقطع تحصیلی را وارد کنید',
    specialty: 'رشته',
    enterSpecialty: 'رشته تحصیلی را وارد کنید',
    startYear: 'سال شروع',
    endYear: 'سال پایان',
    selectYear: 'انتخاب سال',
    status: 'وضعیت',
    inProgress: 'در حال تحصیل',
    completed: 'فارغ‌التحصیل',
    addEducation: 'افزودن تحصیلات',
    companyInformation: 'اطلاعات شرکت',
    enterCompanyDetails: 'جزئیات شرکت خود را وارد کنید',
    companyName: 'نام شرکت',
    enterCompanyName: 'نام شرکت را وارد کنید',
    companyType: 'نوع شرکت',
    selectType: 'انتخاب نوع',
    pharmaceutical: 'داروسازی',
    medicalEquipment: 'تجهیزات پزشکی',
    insurance: 'بیمه',
    address: 'آدرس',
    enterCompanyAddress: 'آدرس شرکت را وارد کنید',
    website: 'وب‌سایت',
    establishedYear: 'سال تاسیس',
    employeeCount: 'تعداد کارکنان',
    enterEmployeeCount: 'تعداد کارکنان را وارد کنید',
    enterPhoneNumber: 'شماره تلفن را وارد کنید',
    description: 'توضیحات',
    tellAboutCompany: 'درباره شرکت خود بگویید',
    reviewInformation: 'بررسی اطلاعات',
    verifyBeforeSubmit: 'لطفا قبل از ثبت، تمام اطلاعات را بررسی کنید',
    profileDetails: 'جزئیات پروفایل',
    educationDetails: 'جزئیات تحصیلی',
    companyDetails: 'جزئیات شرکت',
    name: 'نام',
    contactInfo: 'اطلاعات تماس',
    edit: 'ویرایش',
    submit: 'ثبت نهایی',
    submitting: 'در حال ثبت...',
    role: 'نقش',
    profile: 'پروفایل',
    details: 'جزئیات',
    review: 'بررسی',
    selectUniversity: 'انتخاب دانشگاه',
    searchUniversity: 'جستجوی دانشگاه...',
    noUniversityFound: 'دانشگاهی یافت نشد',
    selectDegree: 'انتخاب مقطع',
    searchDegree: 'جستجوی مقطع...',
    noDegreeFound: 'مقطعی یافت نشد',
    selectSpecialty: 'انتخاب رشته',
    searchSpecialty: 'جستجوی رشته...',
    noSpecialtyFound: 'رشته‌ای یافت نشد',
  },
  ar: {
    selectRole: 'اختر دورك',
    selectRoleDescription: 'اختر الخيار الذي يصفك بشكل أفضل',
    student: 'طالب',
    studentDescription: 'مسجل حاليًا في التعليم الطبي',
    graduate: 'خريج',
    graduateDescription: 'أكمل الدرجة الطبية',
    company: 'شركة',
    companyDescription: 'شركة رعاية صحية أو أدوية',
    continue: 'متابعة',
    back: 'رجوع',
    profileInformation: 'معلومات الملف الشخصي',
    profileDescription: 'أخبرنا عن نفسك',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    email: 'البريد الإلكتروني',
    phone: 'رقم الهاتف',
    dateOfBirth: 'تاريخ الميلاد',
    gender: 'الجنس',
    male: 'ذكر',
    female: 'أنثى',
    other: 'آخر',
    nationality: 'الجنسية',
    city: 'المدينة',
    selectCity: 'اختر المدينة',
    selectGender: 'اختر الجنس',
    required: 'مطلوب',
    province: 'المحافظة',
    selectProvince: 'اختر المحافظة',
    searchProvince: 'بحث عن محافظة...',
    noProvinceFound: 'لم يتم العثور على محافظة',
    searchCity: 'بحث عن مدينة...',
    noCityFound: 'لم يتم العثور على مدينة',
    selectProvinceFirst: 'يرجى اختيار المحافظة أولاً',
    educationInformation: 'المعلومات التعليمية',
    addCurrentEducation: 'أضف تعليمك الحالي والمكتمل',
    educationHistory: 'السجل التعليمي',
    addCompletedEducation: 'أضف درجاتك التعليمية المكتملة',
    education: 'التعليم',
    university: 'الجامعة',
    enterUniversity: 'أدخل الجامعة',
    degree: 'الدرجة',
    enterDegree: 'أدخل الدرجة',
    specialty: 'التخصص',
    enterSpecialty: 'أدخل التخصص',
    startYear: 'سنة البدء',
    endYear: 'سنة الانتهاء',
    selectYear: 'اختر السنة',
    status: 'الحالة',
    inProgress: 'جاري',
    completed: 'مكتمل',
    addEducation: 'إضافة تعليم',
    companyInformation: 'معلومات الشركة',
    enterCompanyDetails: 'أدخل تفاصيل شركتك',
    companyName: 'اسم الشركة',
    enterCompanyName: 'أدخل اسم الشركة',
    companyType: 'نوع الشركة',
    selectType: 'اختر النوع',
    pharmaceutical: 'أدوية',
    medicalEquipment: 'معدات طبية',
    insurance: 'تأمين',
    address: 'العنوان',
    enterCompanyAddress: 'أدخل عنوان الشركة',
    website: 'الموقع الإلكتروني',
    establishedYear: 'سنة التأسيس',
    employeeCount: 'عدد الموظفين',
    enterEmployeeCount: 'أدخل عدد الموظفين',
    enterPhoneNumber: 'أدخل رقم الهاتف',
    description: 'الوصف',
    tellAboutCompany: 'أخبرنا عن شركتك',
    reviewInformation: 'مراجعة معلوماتك',
    verifyBeforeSubmit: 'يرجى التحقق من جميع المعلومات قبل الإرسال',
    profileDetails: 'تفاصيل الملف الشخصي',
    educationDetails: 'التفاصيل التعليمية',
    companyDetails: 'تفاصيل الشركة',
    name: 'الاسم',
    contactInfo: 'معلومات الاتصال',
    edit: 'تعديل',
    submit: 'إرسال التسجيل',
    submitting: 'جاري الإرسال...',
    role: 'الدور',
    profile: 'الملف الشخصي',
    details: 'التفاصيل',
    review: 'المراجعة',
    selectUniversity: 'اختر الجامعة',
    searchUniversity: 'بحث عن جامعة...',
    noUniversityFound: 'لم يتم العثور على جامعة',
    selectDegree: 'اختر الدرجة',
    searchDegree: 'بحث عن درجة...',
    noDegreeFound: 'لم يتم العثور على درجة',
    selectSpecialty: 'اختر التخصص',
    searchSpecialty: 'بحث عن تخصص...',
    noSpecialtyFound: 'لم يتم العثور على تخصص',
  },
};

export type TranslationKey = keyof typeof translations.en;

export function useLanguage() {
  const [language, setLanguage] = useState<Language>('en');
  const [isRTL, setIsRTL] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language') as Language;
      if (saved && (saved === 'en' || saved === 'fa' || saved === 'ar')) {
        setLanguage(saved);
        setIsRTL(saved === 'fa' || saved === 'ar');
        document.documentElement.dir = saved === 'fa' || saved === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = saved;
      }
    }
  }, []);

  const changeLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    setIsRTL(newLanguage === 'fa' || newLanguage === 'ar');
    
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', newLanguage);
    }
    
    document.documentElement.dir = newLanguage === 'fa' || newLanguage === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = newLanguage;
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return {
    language,
    isRTL,
    changeLanguage,
    t,
  };
}
